### ISSUE TITLE
Update /refresh/bind links dynamically created with javascript

### ISSUE THREAD

**Issue by DonPedroo** [Dogstudio/Highway#107]
Hello,

Really digging this library, i have an issue with  dynamic links generated on the page, I have a javascript gallery/slider and each slide has a link to other pages, so when I was testing it out I had hardcoded link URL but when I progressed with my app I am injecting  links  dynamically with javascript, but then highway transitions do not work and I see links attributes are empty, so it is clear links are not registered.

Is there a way to call highway to rescan page for the links?  I found one closed issue where it was recommended to call bind method but it is not clear how exactly to call it and where to find it. 

Thank you.

**Comment by ThaoD5** [comment]
Please, see [the attach method](https://highway.js.org/api.html#core). You can ask Highway to listen to the given array of new links.
