### ISSUE TITLE
New href with highway

### ISSUE THREAD

**Issue by stonners** [Dogstudio/Highway#108]
Hello i have a problem i am using the highway for the transition and i am using paginator which allows em to parse a big data stream, however when i click the button to show more content the <a tags > do not give their href to highway so that highway takes them as external links. I already tried to do "H.attatch (myVar)" but it didn't work
![Capture d’écran 2021-06-08 à 10 17 25](https://user-images.githubusercontent.com/45972860/121149213-c137fa00-c842-11eb-89cb-33c35592259b.png)

**Comment by stonners** [comment]
this.bind is just a test like found in other issues but doesn't work

**Comment by ThaoD5** [comment]
Hello @stonners what exactly are you trying to achieve, or expect to happen ?

**Comment by stonners** [comment]
I expect that when I press my button to add new items, highway takes into account the new href and therefore that the links remain internal, without reloading

**Comment by ThaoD5** [comment]
Have you console.logged your `ctx` array and compared the items in it ? Are there "new" items in the array ?

**Comment by stonners** [comment]
yeah

**Comment by ThaoD5** [comment]
A live demo with console logs would be useful here, could you provide that. ?

**Comment by stonners** [comment]
I display 6 items at a time, and I can clearly see the new items

![Capture d’écran 2021-06-08 à 11 20 47](https://user-images.githubusercontent.com/45972860/121159601-9d2ce680-c84b-11eb-8e63-c081c4dc4a5a.png)

**Comment by ThaoD5** [comment]
What's the forEach for ?

**Comment by stonners** [comment]
it's just a structure, they are containers and in the containers, I have <a> with divs in them

**Comment by ThaoD5** [comment]
On the object.values

**Comment by ThaoD5** [comment]
I think your issue might come from there, you're looping too much on the new link elements you added

**Comment by ThaoD5** [comment]
I would advise you to just do the querySelector on the document + bind once on the ajax update event you have, that should do the trick.
