### ISSUE TITLE
Dynamic links

### ISSUE THREAD

**Issue by Zeindelf** [Dogstudio/highway#13]
Hi!
Thanks for this awesome lib. I do some tests with React (I can't access backend) and works great.

Has any method/event to refresh Highway to listen new links included after navigate?
FYI, I rendering my component on `onEnter` method inside `Renderer` and @1.3.9 version.

Thanks in advance!

**Comment by Anthodpnt** [comment]
Hi! 

Thanks for your feedback, it's really appreciated !

In `Highway.core` there is a `bind` method that takes all the links without `target` and listen them.
So when you instanciate `Highway.Core` you have access to this method.

https://github.com/Dogstudio/highway/blob/master/src/core.js#L94

You could try to use it after rendering your components and let us know if it works.
We didn't take time to check the support for component-based libraries like React.

Best regards,
Anthodpnt

**Comment by Zeindelf** [comment]
Thanks for reply.

Just called `bind()` inside `componentDidUpdate()` & `componentDidMount()` and works like a charm.

Thanks again.

**Comment by Anthodpnt** [comment]
@Zeindelf you'll maybe have to call the `unbind` method as well before calling the `bind` one for safety since the `bind` method takes all the links from the document you might have some double bindings on some list that might cause you some trouble :).
