### ISSUE TITLE
Class constructor Transition/Renderer cannot be invoked without 'new'

### ISSUE THREAD

**Issue by ivandaum** [Dogstudio/highway#33]
Hi guys,

I was trying to follow [the dummy tutorial](https://dogstudio.github.io/highway/get-started.html) with Hightway to implement a simple transition between two pages, but I met the same issue as https://github.com/Dogstudio/highway/issues/6. I'm using Webpack 4 with the UglifyJs plugin.

For the record, I added a `resolve` with `'build/es5/highway.min.js'` in my webpack, and even copied your babel configuration, but it don't seem to fix the issue (not a pro user of Webpack though).

Do you know why I meet this error? Anyway, Hightway looks great an I can't wait to implement it everywhere 🔥!

**Comment by ThaoD5** [comment]
It could be interesting to have your `webpack.config.js` here so that we can maybe figure things out faster, would this be possible for you ?

**Comment by Anthodpnt** [comment]
@ivandaum This is a duplication of #6 I think...

**Comment by ivandaum** [comment]
My bad, I managed to understand what you meant in https://github.com/Dogstudio/highway/issues/6 and fixed it  (I thought the es5 build was auto-implement with the alias)!

For those who, like me, has trouble to understand, it can be fix by adding the follow line in your webpack, after the `exclude: /node_modules/` :

`include: '/node_modules/@dogstudio/higthway/build/es5/hightway.js',`

Anway, thanks a lot guys!

**Comment by ThaoD5** [comment]
@ivandaum glad you found a solution for this, thanks for maybe enlightening other people that could have the same issue :) 

Have a good day !

**Comment by GuillaumeEgloff** [comment]
@ivandaum  I found a better solution to your problem. In your case you exclude completely `node_modules` and if you add a new library you will have to add the new library in `include.`

I prefer to import the right file into javascript:

`import Highway from '@dogstudio/highway/build/es5/highway.js';`

In the documentation: 

`import Highway from '@dogstudio/highway';`

:blush::wave:
