### ISSUE TITLE
New e-commerce site using Highway.js (not an issue)

### ISSUE THREAD

**Issue by wezzou1** [Dogstudio/highway#37]
Check out our newest project [https://carledmond.com/](https://carledmond.com/), using highway.js! 🎉  Thanks for an awesome plugin!

**Comment by ThaoD5** [comment]
Thanks for letting us know @wezzou1 glad you brought this project to life with Highway ! :-)

**Comment by wezzou1** [comment]
@ThaoD5 🎉 🎉

**Comment by ThaoD5** [comment]
Looks really smooth & clean btw, and thanks for being kinda the first external tester giving us a lot of feedback / reporting issues, this really helps us !

**Comment by wezzou1** [comment]
No problem! @ThaoD5 , You guys are awesome!  and response very fast!, I like that :) Thumbs up! Thanks again for some awesome shit!
