### ISSUE TITLE
Facebook Pixel, Google Tag manager etc

### ISSUE THREAD

**Issue by wezzou1** [Dogstudio/highway#38]
Hi, I wonder how it's work with **Google tag manager** and **facebook pixel** in **highway**? Do you guys have any exempel on that? Would nice to have a simple solution in the documentation like you have with google analytics!

```
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', 'your-pixel-id-goes-here');
  fbq('track', 'PageView');
</script>
<noscript>
  <img height="1" width="1" style="display:none" 
       src="https://www.facebook.com/tr?id=your-pixel-id-goes-here&ev=PageView&noscript=1"/>
</noscript>
```

**Comment by ThaoD5** [comment]
We preferred to not have to manage anything of any analytics because the options are various and custom for each project, also, we didn't find it suited to integrate the support of this in Highway :)

Hope this helped you understand how to work with this :-)

**Comment by ThaoD5** [comment]
By the way, we planned to improve the documentation with the infos I am providing you here so that any user can access it and have a path to explore about analytics

**Comment by wezzou1** [comment]
@ThaoD5 alright! nice! Would be nice and better for all off us to quick get access to a simple documentation.
