### ISSUE TITLE
Provide an ES5 compiled version

### ISSUE THREAD

**Issue by alexisferat** [Dogstudio/highway#4]
Hello,

Can you provide an ES5 compiled version of this library?

I have troubles using it with `laravel-mix` because it does not compile scripts from `node_modules`. I tried to override the laravel-mix config to compile your script to ES5 but I have another error:
```
app.js:2106 Uncaught TypeError: Cannot read property 'Renderer' of undefined
    at Object.<anonymous> (app.js:2106)
    at __webpack_require__ (app.js:20)
    at Object.module.exports (app.js:1204)
    at __webpack_require__ (app.js:20)
    at Object.defineProperty.value (app.js:1194)
    at __webpack_require__ (app.js:20)
    at app.js:63
    at app.js:66
```
It seems that the default export is undefined.

If you wish, I can provide you the test project.

Thanks

**Comment by Anthodpnt** [comment]
Hi @alexisferat,

Unfortunately this is not the intention to provide an ES5 version of Highway for the moment.
However  I see in laravel-mix [**documentation**](https://laravel.com/docs/5.6/mix#custom-webpack-configuration) you can provide a custom Webpack configuration.

If it's right you can check the [**basic-polyfill**](https://github.com/Dogstudio/highway/blob/master/examples/basic-polyfill/webpack.config.js) example and the Webpack configuration.
This configuration uses [**babel-loader**](https://github.com/babel/babel-loader) to compile JS from ES6 to ES5. 
It includes all files from a `src` and the `node_modules/@dogstudio/highway` package.

I think you could investigate this trail and let me know if it works.

Best regards,
Anthodpnt

**Comment by Anthodpnt** [comment]
I consider this issue out of the scope of Highway and will close it for now...
