### ISSUE TITLE
Http vs https

### ISSUE THREAD

**Issue by wezzou1** [Dogstudio/highway#40]
Hi again!,

I just mentioned that it is not possible to click on links that have different http/https,

**https -> https** links works fine
**http -> http** links works fine

**https -> http** dosen't work
**http -> https** dosen't work

Of course, all links will be http, or https, but I have managed to get different on some links for now

**Comment by Anthodpnt** [comment]
Hi @wezzou1,

Like you said all links internal to your project SHOULD have the same protocol IMO. If you have links with different protocol thos should be external ones and don’t need Highway then.

I don’t think this is an issue of Highway to not support this kind of behavior but more an issue of logic in how links are managed on the website.

**Comment by wezzou1** [comment]
@Anthodpnt yes, of course, but I think it will be good, if the links dosn't need Highway I think it will act lika a normal link? Let's say, that some link are broken, or something, and if clicking on it, it will return false and create a extern link?

**Comment by wezzou1** [comment]
If the link dosen't support "highway" It's now get an error in console, and dosen't go to click on it. I think it would be better if the site "hard-reload" if the links are wrong

**Comment by Anthodpnt** [comment]
@wezzou1 Highway already hard-reload the link when it’s a 404 error... We cannot do more to know if the link if bad or not... If you want to disable Highway on some links please follow the guide to do it.
