### ISSUE TITLE
History back during fetching causes page content / URL mismatch

### ISSUE THREAD

**Issue by TristanPct** [Dogstudio/highway#41]
Hello,

I noticed that if I go back in my history during page fetching the URL change to the previous one but not the content, Highway shows the new content.

For example, if I go from page A to B everything is good, but then if I'm going to page C and click browser history back button during fetching, I see page B URL but page C content.

**Comment by Anthodpnt** [comment]
Hi @TristanPct,

Thanks for reporting this issue, let us take a look at it and come back to you ASAP.

Best regards,
Anthony

**Comment by joshkirk-zero** [comment]
This is something that is really hard to account for. Popstate events are not cancellable, so if a user clicks forward or back during a transition you can't stop them.

**Comment by joshkirk-zero** [comment]
This is a difficult topic, but definitely worth exploring! We'd have to determine if a popstate event occurs, and if `this.running` is true, handle accordingly. I don't believe any other PJAX lib has solved for this, so it'd be cool to see a solution 👍

**Comment by ThaoD5** [comment]
Hey @joshkirk-zero @TristanPct ,

Earlier last week I took some time to investigate this and couldn't achieve something correct, I indeed am playing with the `this.running` part and doing some conditions but so far I didn't manage to have a correct solution without it being somewhat buggy, maybe my head was a bit too much into it and didn't see the most straight forward solution haha

I will have a look again whenever I have some more time to find a solution to this :-)

Greetings,

**Comment by Anthodpnt** [comment]
Hey guys,

This kind of issue is inherent to the browser. I don't think we could come with a solid solution right now.
I'll close the issue for now...

Thanks
