### ISSUE TITLE
Error when using Highway ES5 version

### ISSUE THREAD

**Issue by Griever12** [Dogstudio/highway#44]
Hello,

I need help to use Highway ES5 version.

When i load it like explain in the doc, i have this error in my console : 

> highway.js:1 Uncaught ReferenceError: define is not defined
    at Object.2 (highway.js:1)
    at o (_prelude.js:1)
    at _prelude.js:1
    at Object.287../components/test-highway (main.js:2)
    at o (_prelude.js:1)
    at r (_prelude.js:1)
    at _prelude.js:1

Any idea to fix that ?

Thanks :-)

**Comment by ThaoD5** [comment]
Hello @Griever12 ,

Would it be possible for you to tell us which highway version you are using, along with the code you wrote to do a highway test ? package.json would also be great to be super effective in the way we could give you a hand.

Greetings,

**Comment by ThaoD5** [comment]
Hello @tsharms, 

What you probably need is the built ES5 version.

We indeed changed the architecture of the files. The compiled ES5 version can now be found inside the `build` folder.
You therefor need now to [resolve the source](https://webpack.js.org/configuration/resolve/#resolve-modules) into your build configuration for highway in order to have the already-compiled file imported.

`"@dogstudio/highway": "@dogstudio/highway/build/highway.min.js"`

Hope this helps, keep me updated :-)

**Comment by tsharms** [comment]
Hi @ThaoD5,

I've checked but it isn't working when I'm using the minified version in the build folder. I've looked at version `2.0.8` and I think I see what the difference is in version `2.1.0`. 

In version `2.0.8` the module is checking if define is a function and exists. In versions `2.1.0` this check is skipped and it is assumed that define is available.

![highway-define](https://user-images.githubusercontent.com/19489787/49806560-559b7180-fd58-11e8-99d8-7278e61570b0.jpg)

Maybe there is a mistake in your build configuration.
Thanks!

**Comment by Anthodpnt** [comment]
Hey @Griever12 @tsharms,

We release the [v2.1.1](https://github.com/Dogstudio/highway/releases/tag/v2.1.1) that should fix the problem.
We were building the ES5 version as an AMD library.
We updated it to build the ES5 version as a UMD library.

Can you please update Highway to this version and let us know if it works now ?
 
Best regards,
Anthodpnt

**Comment by tsharms** [comment]
Hi @Anthodpnt,

I just updated and our code is working again with the latest version! 
Thanks a lot and great work with this library :)

**Comment by Griever12** [comment]
Hello @Anthodpnt @ThaoD5 @tsharms,
Thank you all for reply, al is working fine now.

Very great tool and work :-)
