### ISSUE TITLE
Does it work with React, like Gatsby?

### ISSUE THREAD

**Issue by dingyi** [Dogstudio/highway#50]
Hi, I tried this awesome library in a Gatsby site, but it's not working. Any React examples I can look at?

Thanks!

**Comment by Anthodpnt** [comment]
Unfortunately we don't have any React example so far and we are hoping for some help from the community to make Highway work with most of the trending frameworks including Vue.js or React.

**Comment by ajayns** [comment]
@dingyi Gatsby already handles routes internally between pages and to take control of it further you can use the `gatsby-plugin-transition-link` plugin, any other solution that's from the ecosystem could cause issues with rendering or links.

**Comment by dingyi** [comment]
@ajayns oh good to know! I will try this plugin, thanks.
