### ISSUE TITLE
Can't see all subnav items when the window isn't tall enough

### ISSUE THREAD

**Issue by missmatsuko** [Dogstudio/highway#56]
On [the docs site](https://highway.js.org/), the items under "Examples" in the left sidebar can't be seen if the window isn't tall enough:

<img width="278" alt="Screenshot of left sidebar showing items under 'Examples' getting cut off." src="https://user-images.githubusercontent.com/17884198/58135527-bbc9d180-7bdf-11e9-9483-86f95dc8bb4a.png">

The sidebar isn't scrollable, which would help.

**Comment by ThaoD5** [comment]
Thanks for your input @missmatsuko,
We plan to enhance the documentation in the coming weeks, we will definitely have a look at this. :-) 

Have a great day
