### ISSUE TITLE
Page jerking bug

### ISSUE THREAD

**Issue by adm1t** [Dogstudio/highway#65]
Hello everybody. I ran into the following problem when using the awesome library 'highway.js'. The pages slightly bounce when I navigate the site in any way, except by clicking on links (for example, backward / forward buttons). How can i fix this?

**Comment by Anthodpnt** [comment]
Hello @adm1t 

That doesn't seem to be related to Highway. Highway is only injecting the DOM elements in the body and manages the browser's history. Please make sure this doesn't come from your animations or the way you are removing the old DOM from the body.

Best regards,
Anthodpnt

**Comment by adm1t** [comment]
@Anthodpnt thank you for your comment.
I have no ideas what this might be related to. May be something wrong with the page structure... 
I tried to delete all the animations and use transition code from docs, but the problem still remained. Besides I also found the same bug on one of the hall of fame sites - https://www.realconomy.com/

**Comment by ThaoD5** [comment]
Hello @adm1t ,
I don't encounter any issue with the https://www.realconomy.com/ website;
Highway is not managing any scroll position or animation, so like @Anthodpnt said, it is very unlikable that the issue is coming from Highway itself.

I also have to insist that without further code documentation and a live example; we are unable to provide any further help on this subject.

**Comment by adm1t** [comment]
@ThaoD5 
Well, I reproduced an example of a site where you can observe the problem I described. Look at the link https://adm1t.github.io/highway-issue . 
Among other things, I even recorded a video, that's available on https://youtu.be/AQukaAwcoQ0 .

**Comment by adm1t** [comment]
Finally i found the solution!! 😉
I will send a PR with a fix.

**Comment by tsharms** [comment]
Funny, I'm the developer who has created realconomy.com and encountered the problem in an other project of mine. I was looking for a solution and came across this issue. The fix for this problem is:

```
document.addEventListener('DOMContentLoaded', () => {
    // Fix the page jerking.
    if ('scrollRestoration' in window.history) window.history.scrollRestoration = 'manual';
}
```

(Got it from your pull request) Thanks!
