### ISSUE TITLE
Change route programmatically

### ISSUE THREAD

**Issue by grasmachien** [Dogstudio/highway#71]
Is there a way to change to another page with JS?
document.location.href just reloads the page without using highway.
I'm making something with three.js and want to go to another page when clicking an object.
If there is no built in way to do this I guess I will have to fake a click on the menu items.

**Comment by ThaoD5** [comment]
Hello @grasmachien,

There is a built-in function you can use to achieve that : have a look here 
https://highway.js.org/api.html#core

`HIGHWAY.redirect(href, transition)`
