### ISSUE TITLE
OnLeave destroy

### ISSUE THREAD

**Issue by Stoske98** [Dogstudio/highway#86]
Hey guys, this might be begginer question but I just started with Highway js.
Is there any way to destroy function onLeave({ .. .});

Something like:
customFunction.destroy();

**Comment by Anthodpnt** [comment]
Hey @Stoske98,

Why would you want to destroy de `onLeave` method? Can you please give us a use case where it's required for you to destroy this method?

Best regards,
Anthodpnt

**Comment by Stoske98** [comment]
Thanks for the response. I probably formulated the question in a bad way. I have PIXI js application that I draw on canvas using a function. I call that function onEnter method, but when I leave canvas and all the code remains even if I don't have them on another page, so I guess I need somehow to destroy that function inside of onLeave method. I hope I was clearer this time.

**Comment by Anthodpnt** [comment]
Indeed, all the code running that doesn't need to be run on other pages has to be destroyed or stopped in the `onLeave` or `onLeaveCompleted` method. Those methods are used mostly for this use case, avoid useless code to keep running on all pages after a navigation. It's your job to destroy what has to be destroyed though.

**Comment by Stoske98** [comment]
I understand that, but simply run .destroy() don't help. I tried this way https://github.com/Dogstudio/highway/issues/57 but without results. Canvas still remains on-page, and simple .remove(); from DOM doesn't work since there is still all the code running in the background.

**Comment by Anthodpnt** [comment]
Well, unfortunately this has nothing to do with Highway. The problem seems to come for your own code running in the `onLeave` method of the renderer. We won't be able to help you more on this one. Maybe with a snippet of all the code you have in the `onLeave` method. I'll have to close this issue without more informations since this isn't an issue coming from Highway.

**Comment by Nyshhh** [comment]
Hey legends, 

Thanks for this library! 

I'm also facing a similar issue. I understand how call some JS onEnter (thanks to the superb docs), but not sure how to init (onEnter) AND THEN destroy (onLeave) a piece of JS code. If the docs included a basic example that showed how to do this (creating a constructor), I think that'd be amazing!  

I've followed the #57 example, but get this error --> Uncaught (in promise) TypeError: _Controllers_testController__WEBPACK_IMPORTED_MODULE_1__.default is not a constructor
    at new TestRenderer:

I'm using webpack 4 and am quite new to JS. Any help  / documentation on how to do this is greatly appreciated.

```
import Highway from '@dogstudio/highway/src/highway';
import testController from '../Controllers/testController';

class TestRenderer extends Highway.Renderer {

     constructor(properties) {
        // pass properties into constructor of parent class
        super(properties);

        // initialize class variables 
        this.tController = new testController();
    }

    // Hooks/methods
    onEnter() {
        this.tController.init();
    }
    onLeave() {
        this.tController.destroy();
    }
    onEnterCompleted() {
        // [...]
    }
    onLeaveCompleted() {

        // [...]
    }
}

export default TestRenderer;
````

much respect~

**Comment by Anthodpnt** [comment]
Issue closed because no more informations has been provided.
