### ISSUE TITLE
View within view

### ISSUE THREAD

**Issue by rcobiella** [Dogstudio/highway#88]
Hello!

Is it possible to have a view within another view? I'm not really sure if it's even possible, or if I just can't figure out a way to do it. 

Basically, what I need to do is to route the links contained in a view (A) so they're loaded into another view (B), which is contained inside view A. Is there a way to have two different Core instances running at the same time, to allow having 2 router wrappers?

Possible or not, thank you anyways for this great library!

**Comment by Anthodpnt** [comment]
Hey @rcobiella,

That doesn't seem logic at all. You always have a content that is removed and replaced by another content when a navigation happens. So, what's the purpose to have a view within a view? That's not even a thing we do when we don't use page transitions.

Best regards,
Anthodpnt

**Comment by Anthodpnt** [comment]
Issue closed because no more informations has been provided.
