### ISSUE TITLE
How do I can implement Highway in a Worpress running website? 

### ISSUE THREAD

**Issue by mateusnb** [Dogstudio/highway#94]
Hi Dogstudio/Highway team. Amazing work with Highway. Thanks for it. 

I installed locally highway node. But now Im having some issues for the next steps. 
Shold I create a new project then take the folders upload to my worpress server and then update some files, and voi lá, it ll work ? Which WP files shold I edit? 
Is thre any boilerplate-like samples project implemented with wordpress that I can take as example? 

Thanks for your help

**Comment by ThaoD5** [comment]
Hello @mateusnb ,
The documentation is guiding you through the steps you have to accomplish to get Highway to run.

We are not aware of the logic of your website and the files they contain.
What you should look for is to run the Highway.core function as in the doc, define the transition, and set the `data-router-wrapper` globally, then the `data-router-view` per page.

Further help will be hard to provide as this is very specific per website, even more when it is to be applied to an existing wordpress website.

We do not have a boilerplate ready as this is quite personal to each developer's stack.

**Comment by dashdanilo** [comment]
@mateusnb conseguiu chegar em alguma solução? estou iniciando com a mesma dúvida de integrar o Highway + wordpress
