### ISSUE TITLE
Javascript not working after page transition

### ISSUE THREAD

**Issue by ashehzadgec** [Dogstudio/highway#99]
Hi there

I am quite new to highway.js and got stuck with reloading of JavaScript  after page transition. The only problem I am facing is that my JavaScript is not working after the transition. I tried to workout with renderers but it did  not worked out, I am sure I am missing something but what I do not know. Can someone help me how to reload JavaScript pls. I will really appreciate your help.

Regards,
Shehzad Asif

**Comment by michaelkoelewijn** [comment]
Page specific JS gets called in the renderers.
My guess is you have not correctly setup a renderer for your page.
Also don't forget to call the `done()` function after transitioning as this invokes the renderer.

**Comment by ashehzadgec** [comment]
Hi Michael

Glad someone replied to my question. It would be very kind if you could
just provide a simple example to load the in page js and how to remove out
page js. I am quite new to highway and could not figure it out through the
docs. That's why I need help.

Regards,
Shehzad Asif
